# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170919_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_type',
            field=models.IntegerField(choices=[(0, '선택안함'), (1, 'A형'), (2, 'B형'), (3, 'O형'), (4, 'AB형')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(default='/media/default-picture.jpg', upload_to='avatar'),
        ),
    ]
