# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('post_type', models.CharField(choices=[('F', '자유게시판'), ('S', 'Support You'), ('N', 'Need Help')], max_length=1)),
                ('blood_type', models.IntegerField(blank=True, max_length=1)),
                ('content', models.TextField(verbose_name='본문')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('-modify_date',),
            },
        ),
    ]
