# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170924_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blood_type',
            field=models.IntegerField(blank=True, choices=[(0, '선택안함'), (1, 'A형'), (2, 'B형'), (3, 'O형'), (4, 'AB형')]),
        ),
    ]
